### ISSUE TITLE
call to function "map" failed

### ISSUE THREAD

**Issue by Ranchman42** [devops-made-easy/terraform-aws-kms-share-multi-accounts#1]
Error:

╷
│ Error: Error in function call
│ 
│   on .terraform/modules/kms-share-multi-accounts/main.tf line 5, in resource "aws_kms_key" "devops":
│    5:   tags                = merge(var.tags, map("ApplicationComponent", "kms"))
│ 
│ Call to function "map" failed: the "map" function was deprecated in
│ Terraform v0.12 and is no longer available; use tomap({ ... }) syntax to
│ write a literal map.

Version info: terraform 1.0.7, as of .15 map is no longer a function. This module doesn't appear to be compatible with any version of terraform after .14 as a result.

Is this project still maintained?

**Comment by akloya** [comment]
Thanks for reporting the issue will check on this today and will apply fix.

**Comment by akloya** [comment]
2.0.0 has your fix.. please let us know if its not working as expected.
